chore: fix error when running vitest
RangeError: options.minThreads and options.maxThreads must not conflict

Fixed by adding `--minWorkers=8` to `test:unit` in package.json