Feature/#354 deprecation of jql search and evaluate expression endpoints (#355)
* chore: Vulnerability fix

`npm fix audit`

* chore: fix error when running vitest

RangeError: options.minThreads and options.maxThreads must not conflict

Fixed by adding `--minWorkers=8` to `test:unit` in package.json

* test: define unit test for v3 enhanced search

* feat: implement v3 enhanced search

* chore: fix broken anchor

* test: define unit test for v2 enhanced search

* feat: implement v2 enhanced search

* chore: fix typo in v2

* chore: fix wrong interface name

* test: define unit test for v3 jiraExpressions

Only implemented unit test for the newly added function evaluateJiraExpressionUsingEnhancedSearch()

* feat: implement v3 jiraExpressions

Implemented new function evaluateJiraExpressionUsingEnhancedSearch()

* test: define unit test for v2 jiraExpressions

Only implemented unit test for the newly added function evaluateJiraExpressionUsingEnhancedSearch()

* feat: implement v2 jiraExpressions

Implemented new function evaluateJiraExpressionUsingEnhancedSearch()

* chore: change minWorkers to 1 for vitest

---------

Co-authored-by: Vladislav Tupikin <MrRefactoring@yandex.ru>