Release: v4.1.0 (#346)
* Version 3 simple updates

* CHANGELOG updated

* New API classes added to version3 client

* `Avatar.storeAvatar` method fixed

* Few increment improvements

* Few incremental improvements

* Few incremental improvements

* Few incremental improvements

* Few incremental improvements

* Few incremental improvements

* Feature/#354 deprecation of jql search and evaluate expression endpoints (#355)

* chore: Vulnerability fix

`npm fix audit`

* chore: fix error when running vitest

RangeError: options.minThreads and options.maxThreads must not conflict

Fixed by adding `--minWorkers=8` to `test:unit` in package.json

* test: define unit test for v3 enhanced search

* feat: implement v3 enhanced search

* chore: fix broken anchor

* test: define unit test for v2 enhanced search

* feat: implement v2 enhanced search

* chore: fix typo in v2

* chore: fix wrong interface name

* test: define unit test for v3 jiraExpressions

Only implemented unit test for the newly added function evaluateJiraExpressionUsingEnhancedSearch()

* feat: implement v3 jiraExpressions

Implemented new function evaluateJiraExpressionUsingEnhancedSearch()

* test: define unit test for v2 jiraExpressions

Only implemented unit test for the newly added function evaluateJiraExpressionUsingEnhancedSearch()

* feat: implement v2 jiraExpressions

Implemented new function evaluateJiraExpressionUsingEnhancedSearch()

* chore: change minWorkers to 1 for vitest

---------

Co-authored-by: Vladislav Tupikin <MrRefactoring@yandex.ru>

* Few incremental improvements

* Few incremental improvements

* Few incremental improvements

* The latest Jira Cloud API changes pulled

* Build fixes

* Plans.updatePlan refined

* Wrong types for projectId (#356)

* fix: accept number for all projectIdOrKey

* fix: accept string for projectId

`projectId` is `int64` on Jira API. The API accepts both number string and number.

* fix: duplicate key

* fix: CreateProjectAvatar discrepancy

* CHANGELOG.md updated

* Add new API in `Version2Client` (#357)

* Add boilerplate for new API in Version2Client

* Check and apply changes in Version3Client to Version2Client (#359)

* fix: build error

* chore: update unit test

* fix: missing failFast in SearchAndReconcileRequest

* fix: improvement to updateComment

Forgot to clone the same improvement as addComment.

* feat: v2 IssueBulkOperations

* fix: apply the same improvement to v2 prioritySchemes

* chore: remove unused import

* fix: apply the same improvement as v3

`ProjectKeyAndNameValidation.getValidProjectName` from `unknown` to `string` for improved type safety and usability.

* fix: Apply the same fix as v3

Improvement: Added the avatarId parameter to the IssuePriorities.createPriority method. This parameter will replace iconUrl starting March 16, 2025. The iconUrl parameter is now marked as deprecated.

* fix: apply the same fix as v3

Improvement: Added the avatarId parameter to the IssuePriorities.updatePriority method. This parameter will replace iconUrl starting March 16, 2025. The iconUrl parameter is now marked as deprecated.

* fix: apply the same fix as v3

Fix: Improved the Avatars.storeAvatar method

* fix: apply the same fix as v3

Fix: Improved the IssueTypes.createIssueTypeAvatar method

* fix: apply the same deprecation notes as v3

* fix: align v3 naming to v2

issueSearch and jiraExpression with enhanced search

* Update readme.md

1. moved API token like to API token section
2. added description and link to PAT
3. moved Basic auth to bottom as it's the least preferred way to auth

* fix: rollback changes on v2

Copied v3 feat to v2 by mistake

* Update src/version2/parameters/getAvailableTransitions.ts

add number support to issue ids or keys

Co-authored-by: Vladislav Tupikin <MrRefactoring@yandex.ru>

* Update src/version2/parameters/getBulkEditableFields.ts

add number support to issueIdsOrKeys

Co-authored-by: Vladislav Tupikin <MrRefactoring@yandex.ru>

* fix: startAt and maxResults should be number

* fix: wrong link to v3 in version 2

* fix: incorrect version in anchor

* fix: revert changes on adding v3 only model

* Update src/version3/parameters/searchWorkflows.ts

Co-authored-by: Vladislav Tupikin <MrRefactoring@yandex.ru>

* Update src/version3/parameters/searchWorkflows.ts

Co-authored-by: Vladislav Tupikin <MrRefactoring@yandex.ru>

* chore: revert changes on README.md

move it to another PR

* fix: update *DTO in v3

---------

Co-authored-by: Vladislav Tupikin <MrRefactoring@yandex.ru>

* `bulkFetchIssues` returned back for version2 client

* Clients added to Version2Client

* Clients added to README.md

* Integration test fixes

* Build fix

* Fixes

* Incremental improvements

* Incremental improvements

---------

Co-authored-by: Ness Li <nessgor@users.noreply.github.com>

* Unused code removed

* Incremental improvements

---------

Co-authored-by: Ness Li <nessgor@users.noreply.github.com>